export const UI_TEXT = {
  app: {
    fallbackParent: '母星',
    overviewSuffix: '全景',
    parentSystem: '系统',
    satelliteSystemAvailable: '卫星系统可用',
    displayScale: '展示比例',
    realScale: '真实比例',
    highestQuality: '最高画质',
    brandZh: '深空观测站',
    brandEn: 'DEEP SPACE OBSERVATORY',
    bootStatus: '正在同步观测区域 / SYNCHRONIZING REGIONS',
    returnCurrentRegion: '返回当前观测区域全景',
    soundUnavailable: '音频素材加载失败',
    soundTitle: '艺术化环境音景，并非真实太空声音',
    localStorageUnavailableComment: '本地存储不可用时，只在当前会话内关闭提示。',
    headerSettingsLabel: '观测界面设置',
    regionSwitcherLabel: '观测区域',
    regionDescriptionLabel: '观测区域说明',
    futureRegions: '近邻恒星 / 深空目标：预留',
    targetStatusLabel: '当前观测状态',
    currentTarget: '当前目标',
    parentSystemLabel: '父系统',
    scaleModeLabel: '比例模式',
    qualityLabel: '画质',
    celestialIndex: '天体索引',
    interactionHint: '拖动旋转 · 滚轮缩放 · 点击天体或右侧索引',
    interactionHintDetail: '聚焦后可查看真实观测档案；卫星可返回母星系统。',
    satelliteGuideTitle: '卫星系统已解锁',
    satelliteGuideBody: '从右侧缩进列表或详情面板选择卫星。进入卫星后，“返回母星”会回到当前行星系统，不会直接回全景。',
    gotIt: '知道了',
    landscapeTitle: '建议横屏观测',
    landscapeBody: '旋转设备可减少面板遮挡，保留完整天体构图。',
    orbitControlLabel: '轨道与观测控制',
    resumeOrbit: '继续运行',
    pauseOrbit: '暂停轨道',
    timeSpeed: '时间速度',
    stopCruise: '停止巡航',
    autoCruise: '自动巡航',
    scaleButton: '比例',
    display: '展示',
    real: '真实',
    returnParent: '返回母星',
    returnOverview: '返回全景',
  },
  panel: {
    naturalSatellite: '天然卫星',
    close: '关闭',
    overview: '概览',
    archive: '档案',
    metrics: '参数',
    compare: '对比',
    phenomenon: '现象',
    detailTabsLabel: '天体详情分类',
    shortDescription: '简短描述',
    basicData: '基础数据',
    visualFeatures: '视觉特征',
    targetFeaturesLabel: '目标特征',
    specialPhenomenon: '特殊现象',
    satelliteFeaturesLabel: '卫星特征',
    sourceMaterial: '素材来源',
    realObservationAsset: '真实观测素材或基于观测数据整理',
    proceduralFallbackAsset: '科学资料约束的程序可视化 fallback',
    realIdentity: '真实身份',
    age: '年龄',
    formation: '形成历史',
    discovery: '发现历史',
    composition: '组成',
    surface: '表面 / 外观',
    missions: '关键任务',
    visualizationNote: '可视化说明',
    sources: '资料来源',
    diameter: '直径',
    gravity: '表面重力',
    dayLength: '自转周期',
    yearLength: '公转周期',
    temperature: '温度',
    axialTilt: '轴倾角',
    orbitalDistance: '轨道距离',
    orbitDirection: '轨道方向',
    parentBody: '母天体',
    retrograde: '逆行',
    prograde: '顺行',
    visualSignature: '视觉观测特征 / VISUAL SIGNATURE',
    enhancedVisualNotice: '视觉表现经过增强，不代表实时观测亮度。',
    operationButtons: '操作按钮',
    localScale: '局部系统比例 / LOCAL SCALE',
    satelliteTargets: '次级目标 / SATELLITE TARGETS',
    satelliteSystemControl: '卫星系统控制',
    satelliteScaleLabel: '卫星系统比例',
    satelliteListLabel: '卫星列表',
    guidance: '提示',
    guidanceLabel: '观测提示',
    chooseSatelliteHint: '选择下方卫星或右侧缩进索引，可进入独立镜头、扫描与聚焦流程。',
    archiveHint: '打开“档案”页可查看年龄、形成历史、发现历史、组成、任务与资料来源。',
    returnToSystem: (bodyName: string) => `返回${bodyName}`,
    returnToSystemLabel: (bodyName: string) => `返回${bodyName}系统`,
    closeInfoLabel: '关闭天体信息',
    satelliteReturnHint: (bodyName: string) => `点击“返回${bodyName}”会回到${bodyName}卫星系统，可继续选择同一系统内的其他卫星。`,
    comparisonLabel: (bodyName: string) => `${bodyName}与地球直径轮廓对比`,
  },
} as const
